[2024-09-09T20:27:47.999+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_fetch_raw_amazon_returns_report manual__2024-09-09T20:27:46.417954+00:00 [queued]>
[2024-09-09T20:27:48.018+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_fetch_raw_amazon_returns_report manual__2024-09-09T20:27:46.417954+00:00 [queued]>
[2024-09-09T20:27:48.022+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-09T20:27:48.035+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_fetch_raw_amazon_returns_report> on 2024-09-09 20:27:46.417954+00:00
[2024-09-09T20:27:48.045+0000] {standard_task_runner.py:57} INFO - Started process 318 to run task
[2024-09-09T20:27:48.070+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_fetch_raw_amazon_returns_report', 'manual__2024-09-09T20:27:46.417954+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmp_csh05j4']
[2024-09-09T20:27:48.077+0000] {standard_task_runner.py:85} INFO - Job 254: Subtask run_fetch_raw_amazon_returns_report
[2024-09-09T20:27:48.144+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_fetch_raw_amazon_returns_report manual__2024-09-09T20:27:46.417954+00:00 [running]> on host 5c121da44a2d
[2024-09-09T20:27:48.214+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_fetch_raw_amazon_returns_report' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T20:27:46.417954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T20:27:46.417954+00:00'
[2024-09-09T20:27:48.216+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-09T20:27:48.216+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_fetch_raw_amazon_returns_report.py']
[2024-09-09T20:27:48.225+0000] {subprocess.py:86} INFO - Output:
[2024-09-09T20:27:48.963+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-09T20:27:48.964+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/run_fetch_raw_amazon_returns_report.py", line 15, in <module>
[2024-09-09T20:27:48.965+0000] {subprocess.py:93} INFO -     start_date = values[0][0] + timedelta(seconds=1)
[2024-09-09T20:27:48.965+0000] {subprocess.py:93} INFO - TypeError: can only concatenate str (not "datetime.timedelta") to str
[2024-09-09T20:27:49.005+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-09T20:27:49.024+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-09T20:27:49.028+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_fetch_raw_amazon_returns_report, execution_date=20240909T202746, start_date=20240909T202747, end_date=20240909T202749
[2024-09-09T20:27:49.058+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 254 for task run_fetch_raw_amazon_returns_report (Bash command failed. The command returned a non-zero exit code 1.; 318)
[2024-09-09T20:27:49.086+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-09T20:27:49.128+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
